### PR TITLE
Update code from pending merge on geff-terraform.

### PR DESCRIPTION
**Pull request by sfc-gh-pkommini**
Same as [PR](https://github.com/Snowflake-Labs/terraform-snowflake-aws-geff/pull/20/files#diff-5fd49b9b46b64948accfa8f6f8dcfd53917b39bc4979b490e37aacdab2b1c3e5) from geff-terraform.

### CODE REVIEW

**Review by sfc-gh-afedorov — APPROVED** [review]
lgtm

hoping this is the last and only one with pypi and automated test runs here, soon? would be good to get it going with GitHub Actions so we have some practice for trying them out on dbt :)

**Comment by sfc-gh-pkommini** [comment]
> lgtm
> 
> hoping this is the last and only one with pypi and automated test runs here, soon? would be good to get it going with GitHub Actions so we have some practice for trying them out on dbt :)

@sfc-gh-afedorov: We still don't have mature unit tests. Hoping to get to them later this week. Once we have tests, I'll add github actions to run them, measure coverage, for every push.

**Comment by sfc-gh-afedorov** [comment]
have not ever seen automated "measure coverage" in Python so no pressure on that one, but automated runs would be great on their own

**Comment by sfc-gh-pkommini** [comment]
[This](https://about.codecov.io/blog/python-code-coverage-using-github-actions-and-codecov/) is what I was referring to.

**Comment by sfc-gh-afedorov** [comment]
Shiny!

**Pull request merged**
